
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import QueryProvider from "../core/components/providers/QueryProvider";
import "./globals.css"
import { Toaster } from "sonner"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
 
            {children}
     
          <Toaster
            position="top-right"
            richColors        // màu xanh/đỏ đẹp cho success/error
            closeButton       // hiện nút X
            duration={4000}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
