export const tablesData = [

  // ===== HƯƠNG VIỆT QUẬN 1 =====
  {
    restaurantName: "Hương Việt Quận 1",
    areaName: "Sảnh Chính",
    table_number: "T1",
    min_capacity: 1,
    max_capacity: 2,
    shape: "ROUND",
    is_combinable: false,
    pos_x: 1.00,
    pos_y: 1.00,
    status: "ACTIVE",
    qr_code: "QR_HVQ1_T1",
  },
  {
    restaurantName: "Hương Việt Quận 1",
    areaName: "Sảnh Chính",
    table_number: "T2",
    min_capacity: 2,
    max_capacity: 4,
    shape: "RECT",
    is_combinable: true,
    pos_x: 2.00,
    pos_y: 1.00,
    status: "ACTIVE",
    qr_code: "QR_HVQ1_T2",
  },
  {
    restaurantName: "Hương Việt Quận 1",
    areaName: "Phòng VIP",
    table_number: "VIP1",
    min_capacity: 4,
    max_capacity: 8,
    shape: "LONG",
    is_combinable: false,
    pos_x: 1.00,
    pos_y: 2.00,
    status: "ACTIVE",
    qr_code: "QR_HVQ1_VIP1",
  },

  // ===== HƯƠNG VIỆT QUẬN 7 =====
  {
    restaurantName: "Hương Việt Quận 7",
    areaName: "Sảnh Chính",
    table_number: "T1",
    min_capacity: 2,
    max_capacity: 4,
    shape: "RECT",
    is_combinable: true,
    pos_x: 1.00,
    pos_y: 1.00,
    status: "ACTIVE",
    qr_code: "QR_HVQ7_T1",
  },
  {
    restaurantName: "Hương Việt Quận 7",
    areaName: "Phòng Gia Đình",
    table_number: "F1",
    min_capacity: 4,
    max_capacity: 6,
    shape: "RECT",
    is_combinable: false,
    pos_x: 1.50,
    pos_y: 2.50,
    status: "ACTIVE",
    qr_code: "QR_HVQ7_F1",
  },

  // ===== TOKYO SUSHI LÊ LỢI =====
  {
    restaurantName: "Tokyo Sushi Lê Lợi",
    areaName: "Sushi Counter",
    table_number: "C1",
    min_capacity: 1,
    max_capacity: 2,
    shape: "RECT",
    is_combinable: false,
    pos_x: 1.00,
    pos_y: 1.00,
    status: "ACTIVE",
    qr_code: "QR_TSL_C1",
  },
  {
    restaurantName: "Tokyo Sushi Lê Lợi",
    areaName: "Phòng Tatami",
    table_number: "TATAMI1",
    min_capacity: 4,
    max_capacity: 6,
    shape: "LONG",
    is_combinable: false,
    pos_x: 2.00,
    pos_y: 2.00,
    status: "ACTIVE",
    qr_code: "QR_TSL_TATAMI1",
  },

  // ===== TOKYO SUSHI VINCOM =====
  {
    restaurantName: "Tokyo Sushi Vincom",
    areaName: "Main Dining",
    table_number: "T1",
    min_capacity: 2,
    max_capacity: 4,
    shape: "RECT",
    is_combinable: true,
    pos_x: 1.20,
    pos_y: 1.30,
    status: "ACTIVE",
    qr_code: "QR_TSV_T1",
  },

  // ===== BBQ MASTER PHẠM VĂN ĐỒNG =====
  {
    restaurantName: "BBQ Master Phạm Văn Đồng",
    areaName: "BBQ Hall",
    table_number: "B1",
    min_capacity: 4,
    max_capacity: 6,
    shape: "RECT",
    is_combinable: true,
    pos_x: 2.00,
    pos_y: 1.00,
    status: "ACTIVE",
    qr_code: "QR_BBQ_PVD_B1",
  },
  {
    restaurantName: "BBQ Master Phạm Văn Đồng",
    areaName: "Outdoor BBQ Garden",
    table_number: "G1",
    min_capacity: 6,
    max_capacity: 10,
    shape: "LONG",
    is_combinable: false,
    pos_x: 3.00,
    pos_y: 1.50,
    status: "ACTIVE",
    qr_code: "QR_BBQ_PVD_G1",
  },

  // ===== BBQ MASTER GÒ VẤP =====
  {
    restaurantName: "BBQ Master Gò Vấp",
    areaName: "Sảnh Chính",
    table_number: "T1",
    min_capacity: 2,
    max_capacity: 4,
    shape: "RECT",
    is_combinable: true,
    pos_x: 1.00,
    pos_y: 1.00,
    status: "ACTIVE",
    qr_code: "QR_BBQ_GV_T1",
  },
  {
    restaurantName: "BBQ Master Gò Vấp",
    areaName: "VIP BBQ Room",
    table_number: "VIP1",
    min_capacity: 6,
    max_capacity: 10,
    shape: "LONG",
    is_combinable: false,
    pos_x: 2.50,
    pos_y: 2.50,
    status: "ACTIVE",
    qr_code: "QR_BBQ_GV_VIP1",
  },
];

